### PR TITLE
Add edit functionality to my schedule

### PR DESCRIPTION
**Pull request by AbhiPrasad**
Just replicating https://github.com/uwblueprint/water-festival/pull/129 with new tiling setup

### CODE REVIEW

**Comment by theRoughCode** [comment]
The edit button looks different than the edit button in the designs.  Maybe remove the blue background but make the words blue instead.  For reference: https://www.figma.com/file/abjGlTFfmIQXBpoaRq86rOUG/WWCGF

**Comment by AbhiPrasad** [comment]
Hmm strange, on ios it looks fine. Maybe it's a ios/android difference, I'll look into it

**Comment by AbhiPrasad** [comment]
@theRoughCode This should be good to go for android now, I just changed to component to from a standard react native button to a touchable opacity + text.

**Comment by theRoughCode** [comment]
Great work!

**Pull request merged**
